# Generated by Django 3.1.2 on 2020-11-01 00:53

import apps.candidato.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=apps.candidato.models.upload_foto),
            preserve_default=False,
        ),
    ]
